version: "3.3"

services:
  pgsql:
    build:
      context: .
      args:
        PORT: 5432
        PG_DATA_LOCATION: /var/lib/postgresql/data/pgdata
        PG_PASS: po5tgr35.5ql
    environment:
      POSTGRES_USER: po5tgr3s
      POSTGRES_DB: test
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
volumes:
  pgdata:
    driver: local


